// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import ThemeController from "./theme_controller.js"
application.register("theme", ThemeController)
