default: &default
  adapter:  postgresql
  encoding: unicode
  port:     <%= ENV.fetch("POSTGRESQL_PORT", "5432") %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USER_NAME'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRESQL_DB'] %>
  host: localhost

test:
  <<: *default
  database: <%= ENV['POSTGRESQL_DB'] %>
  host: localhost

production:
  <<: *default
  database: <%= ENV['POSTGRESQL_DB'] %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD") %>
  host:     <%= ENV['POSTGRESQL_HOST'] %>